name: Hello Workflow

# The TRIGGER: What starts the pipeline?
on: [push]

jobs:
  # The JOB: A unit of work
  greet:
    # The RUNNER: The machine executing the job
    runs-on: ubuntu-latest

    steps:
      # STEP 1: Using a pre-made action to copy your repo files to the machine
      - name: Check out repository code
        uses: actions/checkout@v4

      # STEP 2: A standard shell command
      - name: Print greeting
        run: echo "Hello from GitHub Actions!"
      
      # STEP 3: Print current date and time
      - name: Print current date and time
        run: date()
      
      # STEP 4: Print name of the branch
      - name: Print branch name
        run: echo $GITHUB_REF
      
      # STEP 5: List the files in the repo
      - name: List the files in repo
        run: ls -la

      # STEP 6: Print the runner's os
      - name: Print the runner's os
        run: echo $GITHUB_OS