name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  manual_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: echo "Deploying to environment:${{ github.event.inputs.environment }}"