name: Multi Job Test
on: [push]
env:
  APP_NAME: my-app

jobs:
  env-check:
    runs-on: self-hosted
    env:
      ENVIRONMENT: staging
    steps:
      - name: Print Variables
        env:
          VERSION: 1.0.0
        run: |
          echo "App: $APP_NAME"
          echo "Env: $ENVIRONMENT"
          echo "Ver: $VERSION"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
  build:
    runs-on: self-hosted
    steps:
      - name: Print Job name
        run: echo "Building the application"
  test:
    needs: build
    runs-on: self-hosted
    steps:
        - name: Print Job name
          run: echo "Running tests"
  deploy:
    needs: test
    runs-on: self-hosted
    steps:
        - name: Print Job name
          run: echo "Deploying the application"
  job1:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.get_date.outputs.date }}
    steps:
      - id: get_date
        run: echo "date=$(date)" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "The date from job1 was ${{ needs.job1.outputs.build_date }}"