name: Trigger on Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Name
        run: echo "PR check running for branch:${{ github.head_ref }}"
