name: OS Info
on: push

jobs:
  os-info:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print Runner Info
        shell: bash
        run: |
          echo "OS Name: $RUNNER_OS"
          echo "Hostname: $(hostname)"
          echo "Current User: $(whoami)"
          
      - name: Check Pre-installed Tools
        run: |
          docker --version
          python3 --version
          node --version
          git --version