name: Secrets Variables

on: push

jobs:
  scrt_display:
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Print Secret Variables
        run: echo ${{ secrets.MY_SECRET_MESSAGE }}

      - name: Create File
        run: echo "GitHub Actions was here" > action_test.txt

      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: action_test.txt 
  deploy:
    needs: scrt_display
    runs-on: ubuntu-latest
    steps:
      - name: Download Report
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Read Report
        run: cat action_test.txt